Upgrade to pulsar client 2.10.2
spring-projects-experimental/spring-pulsar pull request #193
Opened 2022-11-05 14:36 UTC by cbornet

2022-11-07 03:06 UTC, onobc commented on spring-pulsar/src/main/java/org/springframework/pulsar/core/ConsumerBuilderConfigurationUtil.java
> -		DeadLetterPolicy deadLetterPolicy = getValueToApplyToBuilderAfterLoadConf(builderConf::getDeadLetterPolicy,
Nice improvement @cbornet . Thank you for getting the fix in for the PulsarClient! Do you mind updating the [unit test](https://github.com/spring-projects-experimental/spring-pulsar/blob/bb12a7b666c59af178571eba47bb81e35732c6e1/spring-pulsar/src/test/java/org/springframework/pulsar/core/ConsumerBuilderConfigurationUtilTests.java#L84) to include the newly added fields?

2022-11-07 03:09 UTC, onobc requested changes
Nice improvement @cbornet . Thank you for getting the fix in for the PulsarClient! Do you mind updating the [unit test](https://github.com/spring-projects-experimental/spring-pulsar/blob/bb12a7b666c59af178571eba47bb81e35732c6e1/spring-pulsar/src/test/java/org/springframework/pulsar/core/ConsumerBuilderConfigurationUtilTests.java#L84) to include the newly added fields?

2022-11-07 11:46 UTC, cbornet commented
Sure, I'll update the UT.
Also note that tests seem to fail with Pulsar client 2.10.2... Maybe there's some kind of regression in Pulsar 😞

2022-11-10 15:19 UTC, cbornet commented on spring-pulsar/src/test/java/org/springframework/pulsar/core/ConsumerTestUtils.java
> +	public static Consumer<String> startContainerAndSpyOnConsumer(
For some reason, when upgrading to 2.10.2, the former spyOnConsumer was resulting in a deadlock in `Consumer::batchReceive`.
This is an alternative that works better.

2022-11-10 15:20 UTC, cbornet commented on spring-pulsar/src/test/java/org/springframework/pulsar/core/ConsumerTestUtils.java
> +		Thread.sleep(1000);
We need to give some time for the consumer to initialise.

2022-11-10 15:20 UTC, cbornet commented
@onobc I did the changes. PTAL.

2022-11-10 18:30 UTC, onobc approved these changes
LGTM @cbornet . Thanks for the updates.

2022-11-10 18:47 UTC, onobc commented
Closed via https://github.com/spring-projects-experimental/spring-pulsar/commit/7e91f78fa1fff530e172d5bad450a323973b0d24

2022-11-10 18:47 UTC, closed without merging